version: "3"
services:
  prodigy-indications:
    container_name: prodigy-dailymed
    build: .
    environment:
      - VIRTUAL_HOST=indication-annotation.137.120.31.148.nip.io
      - LETSENCRYPT_HOST=indication-annotation.137.120.31.148.nip.io
      - VIRTUAL_PORT=8080
    volumes:
      - ./data:/app/data

    env_file:
      - .env
    # ports:
      # - 8080:8080
    entrypoint: ./scripts/start.sh