version: "3"
services:
  prodigy-indications:
    container_name: prodigy-indications
    build: .
    environment:
      - VIRTUAL_HOST=indication-annotation.137.120.31.148.nip.io
      - LETSENCRYPT_HOST=indication-annotation.137.120.31.148.nip.io
      - VIRTUAL_PORT=8080
    volumes:
      - ./data:/app/data
      - ./backup:/app/backup
      - ./models:/app/models
    env_file:
      - .env
    tty: true 