version: "3"
services:
  prodigy:
    build: .
    # environment:
    #   - VIRTUAL_HOST=indication-annotation.137.120.31.148.nip.io
    #   - LETSENCRYPT_HOST=indication-annotation.137.120.31.148.nip.io
    #   - VIRTUAL_PORT=8080
    ports:
      - 8080:8080
